name: Build and Publish Docker Images

on:
  push:
    branches:
      - 'build/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Extract image tag from ref
        id: image-tag
        run: |
          ref=${{ github.ref_name }}
          tag=${ref#refs/tags/build/}
          tag=${tag#refs/head/build/}
          echo ref: $ref
          echo tag: $version
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Use the branch name as the tag, e.g., "8.4" for the 8.4 branch.
          tags: ghcr.io/${{ github.repository_owner }}/php-grpc:${{ github.ref_name }}
